image:
  repository: olfa2002/mon-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 3000

# Ajout pour le serviceAccount
serviceAccount:
  create: false
  name: ""
